name: "Autonoma Run Test Trigger"
description: "Trigger a test run in Autonoma AI"
author: "Autonoma"
inputs:
  test-type:
    description: "The type of test to run (folder or test)"
    default: "folder"
  test-id:
    description: "The id of the test or folder to run"
    default: ""
  client-id:
    description: "The client id of an api key generated in Autonoma's platform"
    default: ""
  client-secret:
    description: "The client secret of an api key generated in Autonoma's platform"
    default: ""
outputs:
  status:
    description: "Status of the Autonoma test call (success/failure)"
    value: ${{ steps.notify-service.outputs.status }}
  message:
    description: "Response message from Autonoma"
    value: ${{ steps.notify-service.outputs.message }}
  url:
    description: "URL to view the test run in Autonoma"
    value: ${{ steps.notify-service.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    - name: Notify Service
      id: notify-service
      shell: bash
      run: |
        # Make the API call and capture both response and status code
        response=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "autonoma-client-id: ${{ inputs.client-id }}" \
          -H "autonoma-client-secret: ${{ inputs.client-secret }}" \
          -d '{
            "test_id": "${{ inputs.test-id }}"
          }' \
          "https://api.prod.autonoma.app/v1/run/${{ inputs.test-type }}/${{ inputs.test-id }}")
        
        # Extract the HTTP status code (last line)
        http_code=$(echo "$response" | tail -n1)
        
        # Extract the actual response (all lines except the last)
        api_response=$(echo "$response" | head -n -1)
        
        if [ "$http_code" -eq 201 ]; then
          message=$(echo "$api_response" | jq -r '.message')
          url=$(echo "$api_response" | jq -r '.url')
          
          echo "Service notified successfully"
          echo "status=success" >> $GITHUB_OUTPUT
          echo "message=$message" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
        else
          echo "Failed to notify service (HTTP $http_code)"
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "message=Failed to notify Autonoma, HTTP status: $http_code" >> $GITHUB_OUTPUT
          echo "url=" >> $GITHUB_OUTPUT
        fi
